app_name: "Crivo"
developer_name: "HLC Software"
legal_name: "SEU NOME CIVIL COMPLETO"
support_email: "suporte@seudominio.com"
last_updated: "3 de agosto de 2026"
current_year: 2026
url: "https://crivo.seudominio.com"

exclude:
  - README.md
